
name: Tests 3.14t

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests_3_14t:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.14t"

