
name: "Tests 3.16"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests_3_16:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.16"
      experimental: true

