
name: tests-by-python

on:
  workflow_call:
    inputs:
      python-version:
        description: Python version to run test matrix on
        required: true
        type: string

jobs:
  tests:
    name: py${{ inputs.python-version }} | ${{ matrix.optional_deps }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.python-version }}-${{ matrix.optional_deps }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        optional_deps:
          - "optional"
          - "docs,optional"
          - "data_science,optional"
          - "docs,data_science,optional"
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install system dependencies (in case subpackages that do not have wheels require them)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake zlib1g-dev libjpeg-dev libpng-dev libtiff-dev libwebp-dev libffi-dev
      - name: Install project with python ${{ inputs.python-version }}
        run: |
          uv venv
          uv pip install -e .[${{ matrix.optional_deps }}]
      - name: Run tests with python ${{ inputs.python-version }}
        run: uv run stouputils all_doctests ./stouputils
