
name: "Tests 3.13t"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests_3_13t:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.13t"

