
name: verify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
      - name: Install project
        run: |
          uv venv
          uv pip install -e .
      - name: Ruff check
        run: uv run ruff check ./stouputils

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
      - name: Install project
        run: |
          uv venv
          uv pip install -e .[docs,data_science,optional]
      - name: Pyright check
        run: uv run pyright ./stouputils

  tests_3_12:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.12"

  tests_3_13:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.13"

  tests_3_14:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.14"

  tests_3_13t:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.13t"

  tests_3_14t:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.14t"

  tests_3_15:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.15"

  tests_3_15t:
    uses: ./.github/workflows/tests-by-python.yml
    with:
      python-version: "3.15t"

